CREATE TABLE CUSTOMER
(
    ID   BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCT
(
    ID          BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50)    NOT NULL,
    PRICE       DECIMAL(10, 2) NOT NULL,
    DESCRIPTION VARCHAR(250)
);

CREATE TABLE CART_LINE
(
    PRODUCT_ID  BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    QUANTITY    SMALLINT,
    PRIMARY KEY (PRODUCT_ID, CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID)
);